// Generated by CoffeeScript 1.7.1
var http, paths, util;

http = require('http');

paths = require('./paths.js');

util = require('util');

module.exports = function(method, path, options, cb) {
  var request_options, _paths;

  options = util._extend({}, options || {});
  _paths = paths(options);
  request_options = {
    host: _paths.host,
    port: '80',
    path: path,
    auth: options.user + ':' + options.password
  };
  if (options.headers) {
    request_options.headers = options.headers;
  }
  if (method.toUpperCase() === 'GET') {
    return http.get(request_options, cb);
  } else {
    request_options.method = method;
    return http.request(request_options);
  }
};
